---
-- ***LICENSE_START***
-- Elicit FHHS
-- %%
-- Copyright (C) 2025 - 2026 The Regents of the University of Michigan - Rogel Cancer Center
-- %%
-- PolyForm Noncommercial License 1.0.0
-- <https://polyformproject.org/licenses/noncommercial/1.0.0>
-- ***LICENSE_END***
---
-- Intentionally empty on the greenfield track.
--
-- On the released V2.x track this version created surveyreport.FACT_FHHS_VIEW on top of
-- surveyreport.fact_sections_view. That base view is not part of Survey's schema: Survey's
-- reporting ETL builds it at runtime, and only once a survey exists, so on a fresh database
-- this migration could only ever succeed on FHHS's second boot (start Survey, start FHHS
-- and let it fail here, restart Survey so the ETL runs, restart FHHS). V0.0.7 then dropped
-- the view again because nothing queries it. The greenfield track never creates it, which
-- is what lets a fresh install come up in a single pass.
--
-- The file is kept so the version numbers line up with db/migration-v3: after a V2.x
-- database has been upgraded through that track, ManualSchemaMigrator.repair() realigns
-- its history against these files, and every version it has applied must exist here.
