---
-- ***LICENSE_START***
-- Elicit FHHS
-- %%
-- Copyright (C) 2025 - 2026 The Regents of the University of Michigan - Rogel Cancer Center
-- %%
-- PolyForm Noncommercial License 1.0.0
-- <https://polyformproject.org/licenses/noncommercial/1.0.0>
-- ***LICENSE_END***
---

-- ================================================================================================
-- V0.0.6 (greenfield): nothing to do.
-- ================================================================================================
-- On the released V2.x track this version indexed the single site-wide star in surveyreport
-- (fact_sections, fact_respondents, dim_step, dim_section). That star no longer exists: every
-- survey reports in a schema of its own, created by Survey's ETL the first time the survey is
-- built and named on survey.surveys.report_schema (Survey UC-008 BR-006/BR-007). The indexes --
-- including idx_fact_sections_view_join, the one FHHS's self-joins needed -- are created per
-- survey schema by Survey's template (com.elicitsoftware.etl.Sql.CREATE_SURVEY_SCHEMA_SQL), and
-- fact_respondents is a view. FHHS resolves the schema at request time (UC-005 BR-006).
--
-- The version stays so the greenfield history keeps its numbering; the frozen copy under
-- db/migration-v3 is what an already-upgraded database recorded and is never edited.
-- ================================================================================================
